### PR TITLE
Use UTF-8 Encoding instead 2.0

### PR DESCRIPTION
**Pull request by Slko**
Use UTF-8 encoding in the way that is compatible with Python 2.7 (fixes #25)

### CODE REVIEW

**Comment by jleclanche** [comment]
See #25 for why it's done like this. For the time being, Windows is not supported - just change it locally or run it from a Linux machine.

**Comment by jleclanche** [comment]
I'm open to better suggestions to fix travis btw :/

**Comment by Slko** [comment]
@jleclanche
I fixed the issue in 0b3e4668e4cc1cad3c3dbac5fcb52a26e9c39aad, but travis test still fails because of non-unique ids in BANNER.xml
The same happens with the old version, so that problem shouldn't be related to the PR

**Comment by Slko** [comment]
There is also a weird UNIQUE_ID field which is not unique actually.

**Comment by jleclanche** [comment]
Hm okay, interesting, I'll give it a closer look.

But you're using cElementTree which has been removed in py3. Please stick to ElementTree, it doesn't matter if performance is poor on Py2, it's just for travis.

**Comment by Slko** [comment]
cElementTree seems to work for me on Python 3.4.2, but you are right, there is no reason to use it. The information I used while writing the code is probably out of date or just wrong. Removed "c" and it still works on 3.4.2, 2.7, and in travis.

**Pull request closed without merging**
