### PR TITLE
Add dummy games played/won/lost data resource in account.go

### PR DESCRIPTION
**Pull request by quoing**

### CODE REVIEW

**Comment by jleclanche** [comment]
Can you fix the indenting please? (Make sure to `--amend`, not a separate commit)

**Comment by Mischanix** [comment]
run go fmt, otherwise lgtm

**Comment by quoing** [comment]
Indenting corrected.

**Comment by jleclanche** [comment]
Landed, thanks! Please make sure to rebase your other PR against master.

**Pull request merged**
