### PR TITLE
Stop 'all 9 heroes unlocked' transition when selecting a deck

### PR DESCRIPTION
**Pull request by djkaty**
Becaause it's extraordinarily annoying.

### CODE REVIEW

**Comment by jleclanche** [comment]
gtm, but can you declare those flags properly?

**Comment by Mischanix** [comment]
"Properly" involves storing options to the database.

LGTM

**Comment by jleclanche** [comment]
Ehh, at least declare them in the code no?

**Comment by djkaty** [comment]
What Mischanix said. These options will all be permanently persisted per account in the future, that will be the time to delcare them imho.

**Comment by Mischanix** [comment]
In the end they won't be declared in the server code, only the client cares about what they mean.

**Comment by djkaty** [comment]
BTW it isn't as easy as just making an enum either - the encoding is such that each of 5 64-bit flag fields stores options 31-0, 63-32, .... where the top bit of each option is 'has it been set' and the 2nd is 'what is its value' if 'has it been set' is 1.

**Comment by djkaty** [comment]
Yeah, good point. I was planning to do with them what I do now with presence updates... just re-spew them back to the client without interpreting the data.

**Comment by jleclanche** [comment]
Aight.

**Pull request merged**
