### PR TITLE
Implement Handlers for Store Packets

### PR DESCRIPTION
**Pull request by Ness199X**
* Populated the store with most of the products for sale
* Added a handler for OnPurchaseWithGold, and added a function to save purchased packs to the DB (cards in the packs are stubbed to "Wisp" for classic packs, and "Annoy-O-Tron" for GvG packs)
* Modified the OnOpenBooster function to delete opened boosters and their cards from the DB

### CODE REVIEW

**Comment by synap5e** [comment]
FYI there is trailing whitespace on several lines.

**Comment by jleclanche** [comment]
lgtm at a glance, will want input from @Mischanix

**Comment by Mischanix** [comment]
There's a lot of inconsistent formatting.  Please run `go fmt` on the files you're touching.

**Comment by Ness199X** [comment]
@Mischanix any more input?

**Comment by jleclanche** [comment]
gtm

**Pull request merged**
