### PR TITLE
Matchmaking: various fixes to FindGameResponse and G_RESULT 

### PR DESCRIPTION
**Pull request by djkaty**

### CODE REVIEW

**Comment by Mischanix** [comment]
LGTM.  I think at some point it may be simpler to implement this messaging system the way the data says it does, with a global message queue and routing based on targetId instead of the current channel per-session per-direction implementation.

**Comment by djkaty** [comment]
I tried to write the code to fit in with what was already there but I find some of it extremely annoying. Thoughts I had, your feedback would be appreciated:

- get rid of all the invoke()/methods()-type stuff from each service and make it have a map of method names to functions
- abstract all the proto.Marshal and proto.Unmarshal stuff using a map of methods to message types
- most annoying by far of all: the gameNotification/hostNotification and ClientNotification/ServerNotification channels. The Notification message is some proprietary map string format that added lots of bloat, overhead and unnecessary wrapping/boxing and function calls to the whisper code that could've been really simple. IMHO there should be one channel to/from Kettle, and one channel for _all_ notifications, and that channel should use the bnet.Notification type.

I'm working on ChannelOwner and Channel code now as it's necessary in the new matchmaking protocol, and piping through the existing system will be a real mess, although it can be done.

Thoughts?

**Comment by Mischanix** [comment]
I agree there needs to be a simple queue for the notification type--the way this should work conceptually is that a client registers itself as a listener for messages with a certain `targetId`, and all matching messages get dispatched through that client directly (instead of polling off a queue).  The reason I made it the way it is now is so that there are no synchronization issues (anything reading/writing from the socket for a session or otherwise interacting with session state *must* be done sequentially).  For the RPC services, I think `map[string]func` is inefficient, but it probably doesn't make a huge difference in request latency, so if it's easier to implement the services that way, it's probably for the better (rewriting all the currently-implemented things doesn't sound so fun, however).

**Comment by djkaty** [comment]
For the RPC `map[int]map[int]func` would be sufficient, where the first int is serviceId and the second int is methodId. When binding a service it would return the inner map which would get assigned by the caller to the outer map. Then we could eliminate the Invoke() function altogether. The main reason for this is just to avoid boilerplate code, it's not particularly important.

For the Notification queues, can you give a yay or nay on this:

- Keep gameNotifications,hostNotifications,ClientNotifications,ServerNotifications channels for now (I think in retrospect we still need this for the bnet<->pegasus intra-session communication to avoid blocking)
- Get rid of the Notification type and use `bnet.notification_service.Notification` for internal message passing (which already has fields for type, senderId, targetId etc. defined already). This will cut down on alot of the boxing/unboxing.

- Whenever a session acquires/dissolves an entity (bnet account entity, pegasus account entity, channel id entity, game id entity) it (un)registers it via a function on bnet.Server. These will currently come from responses to Presence.Subscribe (accounts), JoinChannel (game IDs), CreateChannel (channel IDs for friendly challenges). The server must track the client and server-side ObjectIds for the channels as it doesn't send TargetId directly in ChannelSubscriber messages.
- Since EntityId non-reference equality comparison will become a bottleneck, I propose that the list of entity associations in bnet.Server is stored like this:` map[uint64]map[uint64][]*bnet.Session`, where the uin64s are EntityId.High and EntityId.Low. A hypothetical bnet.Server.findSessions is then trivial to implement: `return s.sessionmap[e.High][e.Low]` (with nil checking).

**SendNotification/OnNotificationReceived:**
- Add a send-only notification queue to bnet.Server:`notificationQueue chan<- *bnet.notification_service.Notification`. This will be serviced by a for select in a goroutine that will just use findSessions() to send the notifications to all subscribed sessions.

- Where items are pushed to ServerNotifications where the target is not self (SendNotificaiton [currently just used for whispers]): replace the NewNotiifcation builder and queueing with `s.server.notificationQueue <- req`. This gets these messages out of the messy ServerNotifications->hostNotifications->gameNotifications->ClientNotifications chain when it's not necessary.

- Where items are pushed to ServerNotifications where the target is self (FindGame [FindGameResponse], ProcessClientRequest [util packets]): don't modify for now (this is intra-session bnet<->pegasus communication)

**ChannelState (for ChannelSubscriber.NotifyAdd/NotifyChannelUpdateState, Presence, ChannelOwner and Channel services):**
- Change PresenceMgr.Subscribe to just add itself as a subscriber to the entity in bnet.Server. Get rid of the presence table from the database. Ditto PresenceMgr.Unsubscribe. Might even be able to just move this stuff to PresenceService altogether.
- Get rid of the queue in ChannelSubscriberService and turn NotifyAdd and NotifyChannelUpdateState into helper functions that return ready-made ChannelState objects (will involve some re-factoring)
- Since these updates are different to notifications, we need a 2nd queue `bnet.Server.channelStateQueue chan<- *ChannelState`
- GlobalPresenceMgr.broadcastUpdate becomes a one-line function that pushes a new ChannelSate built by the NotifyChannelUpdateState helper into `s.server.channelStateQueue`.

Channel and ChannelOwner are not yet implemented but this should remove the need to duplicate PresenceMgr-style code and have another set of session lists, which is part of the point.

By using a for select in the queue pump for both the new bnet.Server queues, we ensure asynchronicity. Socket concurrency safety is already accounted before because pumpPacketQueue ensures updates are sent sequentially and not in parallel.

**Net result:**
- One map of entity IDs to subscribed sessions in bnet.Server
- One queue for outbound notifications in bnet.Server (will send OnNotificationReceived to subscribers)
- One queue for outbound ChannelState adds and updates in bnet.Server (will send NotifyAdd or NotifyChannelUpdateState to subscribers)
- Presence gets dealt with semi-automatically, without the need for a database of much of a manager
- Channel and ChannelOwner can be slotted in much more easily
- Notifications to non-self do not go through the bnet<->pegasus queue pipe with unnecessary boxing/unboxing
- Intra-session queues for bnet<->pegasus are kept
- More or less (hopefully) single code path for all of the above

Please note this approach improves performance and gives a single code path at the expense of additional memory consumption as all the subscriptions are stored in memory instead of the database. Adding a database table for it could be done in the future but is slightly awkward due to the need to track bnet.Session pointers.

Please note also this is my current best 'guestimate'. When I implement it I may find it doesn't quite work as expected, it's a big design change.

Feedback/thoughts? :)

**Comment by Mischanix** [comment]
>`map[int]map[int]func`

`map[int][]func` is probably best, the ids for methods are mostly sequential from 0.

>EntityId non-reference equality comparison will become a bottleneck

I have another project that uses 128-bit hashes (via `struct { A, B uint64 }`) as map keys and it's not an issue at all.  A nested map is probably slower, but definitely more complex.

Aside from that, this sounds good to me.

**Comment by djkaty** [comment]
The issue is that you can't use entity.EntityId as a map key (I already tried), it says its an unsupported type, I'm guessing because it contains pointers rather than value types.

**Comment by djkaty** [comment]
How do you propose to solve the intra-session queues problem? I have thought about it and looked through the source code for some hours this afternoon and I'm yet to come with a good solution.

**Comment by Mischanix** [comment]
Yes, you need to use a `struct { Lo, Hi uint64 }` type that gets converted from the protobuf type (i have sooo much hate for protobuf for using pointers everywhere...).  I need to look at the queues problem myself, not sure what all needs to be replaced

**Comment by djkaty** [comment]
Alright, I thought of that, but there is soooooo much boxing and unboxing if we do that... I really think the map of maps would be more performant, although I can't say for sure without testing. It will for sure add a lot of code boilerplate because Entitys everywhere.

**Pull request merged**
