### PR TITLE
Optionally get the bind address from the command line

### PR DESCRIPTION
**Pull request by synap5e**

### CODE REVIEW

**Comment by Mischanix** [comment]
Please use the [flag](http://godoc.org/flag) package for this.

**Comment by synap5e** [comment]
Thanks, that makes it much more elegant :smile: 

How's this? I also changed it to report errors in binding in case an invalid bind address is specified

```
[simon@tyr stove]$ go run stove.go 
Listening on localhost:1119 ...
^Cexit status 2

[simon@tyr stove]$ go run stove.go -help
Usage of /tmp/go-build255679913/command-line-arguments/_obj/exe/stove:
  -bind="localhost:1119": The address to run on
exit status 2

[simon@tyr stove]$ go run stove.go -bind
flag needs an argument: -bind
Usage of /tmp/go-build146754524/command-line-arguments/_obj/exe/stove:
  -bind="localhost:1119": The address to run on
exit status 2

[simon@tyr stove]$ go run stove.go -bind 0.0.0.0
Listening on 0.0.0.0:1119 ...
^Cexit status 2

[simon@tyr stove]$ go run stove.go -bind 0.0.0.0:2000
Listening on 0.0.0.0:2000 ...
^Cexit status 2

[simon@tyr stove]$ go run stove.go -bind thatsnotavalidtarget
Listening on thatsnotavalidtarget:1119 ...
listen tcp: lookup thatsnotavalidtarget: no such host
```

**Comment by jleclanche** [comment]
`-help` should be `--help`, and `-bind` should be positional rather than a named arg

**Comment by Mischanix** [comment]
`--help` is not how the plan9 argument system works, which package flag is based on.

**Comment by jleclanche** [comment]
Yeah so I saw.

**Comment by synap5e** [comment]
So should bind be positional or not?
flags doesn't do positional beyond flags.Args() to get non-flag args so I would have to do the help + default values myself.

**Comment by Mischanix** [comment]
No, it shouldn't be positional.

**Pull request merged**
